spring:
  #  profiles:
  #    active: development
  datasource:
    url: jdbc:mysql://localhost:3306/schema
    username: root
    password: Password123!
    driverClassName: com.mysql.cj.jdbc.Driver
  mail:
    host: 172.21.1.101
    port: 25

  messages:
    basename: message/message

  thymeleaf:
    suffix: .html

# Spring Security
notice.security.https: false


#一覧の１ページあたりの最大件数
list.max.count : 10

#ページャの数字ボタン数
pager.btn.count : 3

