spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schema?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Password123!
    driverClassName: com.mysql.cj.jdbc.Driver

  messages:
    basename: message/message

  thymeleaf:
    suffix: .html

# Spring Security
notice.security.https: false


#一覧の１ページあたりの最大件数
list.max.count : 15

#ページャの数字ボタン数
pager.btn.count : 3

